### ISSUE TITLE
Bug report -> display_information name causes confusion about max length

### ISSUE THREAD

**Issue by BSouzaDock** [slack-samples/bolt-python-custom-function-template#12] opened 2024-04-12 19:41 UTC
I was getting the error below while configuring a manifest file:

`{"ok":false,"error":"invalid_manifest","errors":[{"code":"failed_constraint","constraint":{"type":"max_length","expected":35,"got":41},"message":"must be less than 36 characters","pointer":"\/display_information\/name"}]}`

After debugging the logs and carrying out several tests, I discovered that the app always places the string (local) at the end of the "display_information" key, so even placing the correct number of characters, if it has between 29 ~ 35 characters it will generate this error.

**Comment by zimeg** [comment] 2024-04-12 20:53
Hey @BSouzaDock 👋 As you've found, this is caused by appending the ` (local)` tag to any apps running with `slack run` with the actual error coming from [apps.manifest.validate](http://api.slack.com/methods/apps.manifest.validate). We'll look into improving this error message but right now this is expected behavior to differentiate between apps used in production and those used for development.

This is a super helpful issue to reference for this `display_information` manifest error, but because it originates from the API and isn't caused by this sample I'll close this issue. Please feel free to follow up with any other questions or suggestions on this error! I'll also share any updates I find on this here.

**Closed by zimeg** 2024-04-12 20:53 UTC
Labels: bug, wontfix
